### ISSUE TITLE
Notifications: bad link from discord to submit page

### ISSUE THREAD

**Issue by LidaChk** [rolling-scopes/rsschool-app#1435] opened 2022-05-18 18:17 UTC
**Describe the bug**
bad link from discord to submit
https://app.rs.school/course/student/cross-check-submit?course&#x3D;js-fe-2022Q1&amp;taskId&#x3D;1501

**To Reproduce**

1. recieve notification 'Your task has been reviewed by crossCheck' from RS APP Bot in discord
2. Click on link 'Details can be found at: '
4. See error 'No Access
Probably you do not participate in the course. Please register or choose another course.'

**Expected behavior**
Open students page with reviews on task

**Screenshots**
![image](https://user-images.githubusercontent.com/20344968/169112327-a436d1cf-7085-47c1-81c2-333885f37cde.png)
![image](https://user-images.githubusercontent.com/20344968/169115941-d1954c48-e3a7-4d86-b1da-970191792ca1.png)

**Device (please complete the following information):**
Firefox
Chrome

**Comment by aaliakseyenka** [comment] 2022-05-18 18:58
can't reproduce, link removed until further investigation

**Comment by aaliakseyenka** [comment] 2022-05-18 19:36
thanks for report. should be fixed

**Closed by aaliakseyenka** 2022-05-18 19:36 UTC
