### ISSUE TITLE
Endless email verification

### ISSUE THREAD

**Issue by marblehands** [rolling-scopes/rsschool-app#2345] opened 2023-11-06 21:24 UTC
**Describe the bug**
The app requires mail verification several times after successfully verifying previously.

**To Reproduce**

1. Open RS app profile (@marblehands)
2. See the message "Email is not verified. Send confirmation email?"
3. Click on the link "Send confirmation email?"
4. Verify email successfully
5. Open profile again
6. See the message "Email is not verified. Send confirmation email?" ... this was repeated 3 times.

**Expected behavior**
Successful verification of emails happens once.

**Screenshots**
<img width="1466" alt="Screenshot 2023-11-06 at 22 20 21" src="https://github.com/rolling-scopes/rsschool-app/assets/7912739/3c344cb2-2b0c-4d9f-b724-0a688775aa24">

**Device (please complete the following information):**

- OS: MacOs Monterey Version 12.5 
- Browser Google Chrome
- Version 119.0.6045.105

**Additional context**
Thank you for your awesome work on the RS APP ❤️

**Comment by I-vasilich-I** [comment] 2023-11-16 11:23
looks like the issue caused by any update that user makes on profile

- confirmed email
![Screenshot from 2023-11-16 13-42-21](https://github.com/rolling-scopes/rsschool-app/assets/67139199/6ad3ad55-fe10-4400-bcbb-bbae16759a05)
- after I made changes
![Screenshot from 2023-11-16 13-43-06](https://github.com/rolling-scopes/rsschool-app/assets/67139199/ddeda37c-a7b7-4965-9833-63e99c717ce4)

So, it looks like profile update(`updateProfileFlat`) deletes email connection, more precisely `updateEmailChannel` does it, because on partial update email is `undefined`
![Screenshot from 2023-11-16 14-02-55](https://github.com/rolling-scopes/rsschool-app/assets/67139199/597eb23a-e814-4e22-a14d-c9652c3784d9)
![Screenshot from 2023-11-16 14-04-27](https://github.com/rolling-scopes/rsschool-app/assets/67139199/bf1ef23f-057d-4ccc-a6cd-b0867fe330e8)

I guess this might fix it, but I'm not sure if it's a proper way to handle it, and I can't test it locally because I have no clue how to run notifications services locally, if it's even possible:
![Screenshot from 2023-11-16 14-09-53](https://github.com/rolling-scopes/rsschool-app/assets/67139199/4deb7466-e7ea-4b9b-95be-316b0268e365)

in case user set email to `''` it'll work as expected - connection will be removed

BTW this issue is a duplicate of [issue#2212](https://github.com/rolling-scopes/rsschool-app/issues/2212)

**Closed** 2023-11-29 14:07 UTC
